library(R2jags)
setwd("C:\\Users\\milosma\\OneDrive\\Documents\\MSc in Data Analytics\\Year 3 - Semester 2\\STAT40850 - Bayesian Analysis\\Computer Labs\\Computer Lab 1")
volcano <- list(x=421, phi=64, theta0=379, phi0=400)
jmodel <- jags.model(file="dating.model", data=volcano)
samps <- jags.samples(jmodel, "theta", n.iter=10000)
plot(density(samps$theta))
plot(samps$theta, t='l')
mean(samps$theta)
sd(samps$theta)